# Generated by Django 4.1 on 2023-09-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargecard',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
