# Generated by Django 4.1 on 2024-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_offers_type_of_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offers',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('V30 Offer', 'V30 Offer'), ('Y27s Offer', 'Y27s Offer'), ('VTop Offer', 'VTop Offer'), ('Monthly Offer', 'Monthly Offer')], max_length=800),
        ),
    ]
