# Generated by Django 4.1 on 2023-09-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_rename_assigned_rechargecard_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recharge_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.rechargecard'),
        ),
    ]
