# Generated by Django 4.1 on 2023-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_customer_recharge_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCardOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('Ncell', 'Ncell'), ('Ntc', 'Ntc'), ('Smart Cell', 'Smart Cell'), ('Others', 'Others')], max_length=400)),
                ('amount', models.IntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')])),
                ('type_of_offer', models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('Weekly Offer', 'Weekly Offer')], max_length=800)),
                ('offer_condition_value', models.CharField(max_length=500)),
                ('sale_numbers', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='phone_price_type',
            field=models.CharField(choices=[('Below 15000', 'Below 15000'), ('Above 15000', 'Above 15000')], default='Above 15000', max_length=800),
        ),
        migrations.AddField(
            model_name='offers',
            name='sale_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prize_details',
            field=models.CharField(default='Happy Dashain and Tihar', max_length=900),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='phone_price',
            field=models.CharField(choices=[('Below 15000', 'Below 15000'), ('Above 15000', 'Above 15000')], default='Above 15000', max_length=800),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer')], max_length=800),
        ),
        migrations.AlterField(
            model_name='rechargecard',
            name='amount',
            field=models.IntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')]),
        ),
        migrations.AlterField(
            model_name='rechargecard',
            name='provider',
            field=models.CharField(choices=[('Ncell', 'Ncell'), ('Ntc', 'Ntc'), ('Smart Cell', 'Smart Cell'), ('Others', 'Others')], max_length=400),
        ),
    ]
