# Generated by Django 4.1 on 2023-10-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_alter_offers_offer_condition_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargecardoffer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rechargecardoffer',
            name='provider',
        ),
    ]
