# Generated by Django 4.1 on 2023-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0010_rechargecardoffer_amount_rechargecardoffer_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
