# Generated by Django 4.1 on 2023-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0010_rechargecardoffer_amount_rechargecardoffer_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargecard',
            name='cardno',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
