# Generated by Django 4.1 on 2023-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_alter_customer_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='validto',
            field=models.CharField(choices=[('V Series Offer', 'V Series Offer'), ('Y Series Offer', 'Y Series Offer'), ('All', 'All')], default='All', max_length=800),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('Y27s Offer', 'Y27s Offer')], max_length=800),
        ),
    ]
