# Generated by Django 4.1 on 2023-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0013_offers_validto_alter_offers_type_of_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='imeino',
            name='model',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
