# Generated by Django 4.1 on 2023-12-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0014_imeino_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imeino',
            old_name='model',
            new_name='phone_model',
        ),
    ]
