# Generated by Django 4.1 on 2024-04-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0015_rename_model_imeino_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_see_admit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='see_admit_card',
            field=models.Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('Y27s Offer', 'Y27s Offer'), ('VTop Offer', 'VTop Offer')], max_length=800),
        ),
    ]
