# Generated by Django 4.1 on 2024-04-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0016_customer_has_see_admit_card_customer_see_admit_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='has_see_admit_card',
            new_name='just_passed_see',
        ),
    ]
