# Generated by Django 4.1 on 2024-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0017_rename_has_see_admit_card_customer_just_passed_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('V30 Offer', 'V30 Offer'), ('VTop Offer', 'VTop Offer')], max_length=800),
        ),
    ]
