# Generated by Django 4.1 on 2024-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0018_alter_offers_type_of_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='see_admit_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
